### ISSUE TITLE
Combine blocks of same module, timeslot, location together & remove duplicates

### ISSUE THREAD

**Issue by fustilio** [nusmodifications/nusmods#1204]
### Is your feature request related to a problem? Please describe.
Figure 1
![image](https://user-images.githubusercontent.com/23294131/46527326-790eef80-c8c3-11e8-8e81-198437f78be5.png) 
Figure 2
![image](https://user-images.githubusercontent.com/23294131/46527412-b2dff600-c8c3-11e8-9327-5991c7bb41fc.png)

As shown in figure 1, the module PL2131 has repeated blocks of the same time slot. This is probably because of the data on cors figure 2. 

### Describe the solution you'd like
The blocks could also be joined together. For example, the blocks for weeks 9/11, 3/5 and 7 could be combined to one block with weeks 3/5/7/9/11 provided that the locations are the same.

**Comment by taneliang** [comment]
This seems to have only started happening after a recent scrape (last week?), probably because CORS now displays tutorials in separate rows for whatever reason, which is shown in Figure 2. Here's a link to the CORS page: https://myaces.nus.edu.sg/cors/jsp/report/ModuleDetailedInfo.jsp?acad_y=2018/2019&sem_c=1&mod_c=PL2131

We can either wait and see if CORS fixes this issue on their side, or we'll have to combine the tutorials ourselves.

**Comment by ZhangYiJiang** [comment]
For a quick fix we can have the frontend merge all of the lessons. It looks like this is affecting actual users, so let's push out a quick fix for this maybe?

**Comment by ZhangYiJiang** [comment]
New scraper should not suffer from this issue, so closing
