### ISSUE TITLE
Hide tutorial slots functionality

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#167]
From Nguyen Cao Nhat Linh: "Hide all labs and tutorials" so that some of us can fit the modules into the timetable first for bidding. It looks cluttered here with all the tutorial and lab sessions showing"

@ahbeng I remember this was implemented sometime back but it got removed. Any idea why?

**Comment by xinan** [comment]
I don't think this is very useful because sometimes one may have 2 modules that do not have any clash in exam time or lecture time, but their tutorial or lab timings might clash. In that way even though he got those two modules, he might still need to drop one of them because there is no suitable tutorial slots for his situation.

**Comment by yangshun** [comment]
Agree with @xinan it's not really useful. Closing this.
