### ISSUE TITLE
CS1101S Prerequisite Error for Module Planner

### ISSUE THREAD

**Issue by seanlowjk** [nusmodifications/nusmods#1872]
### Describe the bug
When Choosing Modules which have CS1101S cleared as a prerequisite in the previous semester, warnings will pop up that you have not taking CS1010 or its equivalent, despite the fact that CS1101S is the equivalent modules for CS1010.

### Expected behavior

No warnings to be given when modules which have CS1101S as its prerequisite are selected.

### Screenshots

![image](https://user-images.githubusercontent.com/42912708/59974525-de387b80-95df-11e9-8ed9-c68e19aeb00e.png)

**Comment by ZhangYiJiang** [comment]
This is unlikely to be fixed because it is impossible to encode which modules are equivalent for the purpose of fulfilling prerequisites since two modules may be equivalent for some purposes but not others. The issue is with the school's data, specially the prerequisites of those modules you're looking at, so we'll need to ask the school to fix their data here. 

Since you took CS1101S in the first semester, a workaround may be to add CS1010 as a exemption.  We might also think about adding aliasing, although as mentioned above this may have dangerous edge cases.
