### ISSUE TITLE
Unable to download shared timetable without importing

### ISSUE THREAD

**Issue by jonchan51** [nusmodifications/nusmods#2042]
### Describe the bug

Attempting to download an shared modsn.us timetable without importing results in downloading the saved timetable

### To Reproduce

1. Click on any modsn.us timetable link
2. Click on Download, select any option
3. See that the downloaded timetable is the saved timetable and not the shared timetable

### Expected behavior

Expected to download the shared modsn.us timetable even though it is not imported.

### Additional Context
Can be 'bypassed' by importing the timetable but that replaces the local timetable, and there is no indication that it is a solution

**Comment by jonchan51** [comment]
If this is expected behaviour I would like to take this

**Comment by ZhangYiJiang** [comment]
Yeah, this is because the code that encodes the timetable into URL takes the timetable config directly from the Redux store state, instead of taking in the current timetable as a parameter. It's definitely not impossible to fix, but it is a bit tricky. Feel free to take this issue, and reach out if you need help.
