### ISSUE TITLE
Filter modules by ULR type such as SSA, GEK/GEM.

### ISSUE THREAD

**Issue by 9gix** [nusmodifications/nusmods#223]
In the past, we are able to show list of GEM/GEK or SSA modules offered. This was somehow removed. Can we have it back, I find it very useful to browse such modules?

For GEM/GEK, We can find it at http://www.nus.edu.sg/registrar/gem/list-all-general-education-modules

**Comment by 9gix** [comment]
For GEM/GEK, We can find it at http://www.nus.edu.sg/registrar/gem/list-all-general-education-modules

**Comment by yangshun** [comment]
Hey @9gix , great suggestion! You are welcome to fork and make a pull request adding this feature :smile:

**Comment by ahbeng** [comment]
Hi Eugene, this wasn't removed, but it was derived from CORS categorization, e.g. [CORS GEM info listing](https://myaces.nus.edu.sg/cors/jsp/report/GEMInfoListing.jsp). The types would appear once CORS has been updated for AY15/16, that's why currently they're all listed as "Not in CORS".

I suppose for GEM and SSA there could be a secondary source for categorization like the one you pointed out, or simply using the module code, but not sure if there are any edge cases for that. I don't think there would be an easy way to determine the other types like "Breadth / Unrestricted Elective Modules outside Student's Faculty" and "Cross-Faculty Modules" without CORS data though. Given that CORS should be updated soon, I'm not sure this would be very useful going forward.

Being able to filter by module code/title free text search may be a more flexible way of addressing this issue.

**Comment by 9gix** [comment]
Hmm... I like the idea of using the text search. If we were to use the existing search at top bar. Perhaps something like this one would be good, what do you think? (simplified pattern match)
- `GE` will match GExxxx (Geography)
- `GE*` will match GEKxxxx, GEMxxxx.
- `GE*1` will match GEK1xxxx, GEM1xxxx
- `SS*` will match SSAxxxx, SSBxxxx, SSDxxxx, SSExxxx, SSMxxxx, SSSxxxx, etc...
- `CS` will match CSxxxxx
- `ge` will match any module with the word "General", "Genes", "Geography", "management", etc...

> So When users search with CAPS-case perhaps we can assume that they are trying to filter by the module code.

**Comment by ZhangYiJiang** [comment]
I think this can be closed now that R implements text based searching. Since it prioritizes module codes, this makes it pretty easy to find those modules.
