### ISSUE TITLE
Distinguish "No exam timetable data" from "No Exam"

### ISSUE THREAD

**Issue by xinan** [nusmodifications/nusmods#264]
At this period of time many modules on CORS are updated for the next semester but not the exam timetable. (I think this happens every year.) Instead of showing "No exam" for all of them, maybe we should be able to distinguish the situation of "No exam" and "No exam timetable info can be retrieved".

**Comment by yangshun** [comment]
Workaround: 97c6f15

**Comment by ahbeng** [comment]
So the issue is that the exam isn't necessarily populated in CORS but may be populated in exam timetable later?

I'm not sure it'd be better to display this as an inline message vs. a temporary global message when the exam timetable hasn't been published. Since it'd just be the same for every module that doesn't have an exam time listed in CORS yet.

But maybe a tooltip note for "No Exam" would be less intrusive. Would need to update NUSMods API to distinguish between no exam in CORS and no exam in exam timetable.

**Comment by xinan** [comment]
Hmm, it is not that no exams in CORS but there is in exam timetable. It is that the module informations are updated first, and the exam information are only updated when the CORS schedules are announced. So during this gap, all modules shows "No exam".

**Comment by yangshun** [comment]
I think it'll be fine to keep it undefined rather than giving the user potentially false information. Perhaps render a dash? 😂

**Comment by taneliang** [comment]
@yangshun Uhoh #571 changes this back to "No Exam". Should it be changed back to "Exam: -"?

**Comment by taneliang** [comment]
NUSIT informed us that their system only knows if there is an exam if someone sets the exam date on the system, and thus it won't be possible to know if the mod actually doesn't have an exam or if the exam date is just unknown. They also mentioned that exam dates can be set and changed at any time, even during the semester, and so unfortunately the assumption that all the exam dates are set at once is not true.
