### ISSUE TITLE
The relationship between CS4240 and CS3240 is not shown in the prerequisite tree

### ISSUE THREAD

**Issue by w-yuchen** [nusmodifications/nusmods#2686]
### Describe the bug

CS4240's Prerequisite Tree does not show any prerequisites despite "CS3240 and (MA1301 or A-level / H2 Mathematics)" being listed as prerequisites. In CS3240's page, CS4240 is also not listed as a module needing CS3240. 

### To Reproduce

1. Go to [CS4240](https://nusmods.com/modules/CS4240/interaction-design-for-virtual-and-augmented-reality)
2. Scroll down to Prerequisite Tree
![image](https://user-images.githubusercontent.com/32015928/83944947-e1049e80-a839-11ea-9a84-9939ffe037b8.png)

Also, 
1. Go to [CS3240](https://nusmods.com/modules/CS3240/interaction-design)
2. CS4240 is not shown. 
![image](https://user-images.githubusercontent.com/32015928/83945047-7acc4b80-a83a-11ea-99cc-6c019120f0c8.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/32015928/83944963-f8438c00-a839-11ea-99bf-92a610f1e782.png)

CS3240 is listed as a prerequisite both in the descriptions above and on Luminus, so it should appear in the prerequisite tree for CS4240. Similarly, CS4240 should appear in the prerequisite tree for CS3240.

**Comment by taneliang** [comment]
Thanks for reporting this!

Our prerequisite tree is constructed by parsing that prerequisite string. Because CS4240's prereq string includes some text that our parser doesn't recognize, the parser bails and doesn't record any prereq information for CS4240.

Ideally we'd want to get machine-readable prereq data directly from internal NUS APIs, but I don't think we'd get that anytime soon.

We can improve this now by attempting to handle these A-Level requirements in the parser. Another example of a module where the parser bails is [MA1101R](https://nusmods.com/modules/MA1101R/linear-algebra-i).

This can be handled in the prereq string [normalizer](https://github.com/nusmodifications/nusmods/blob/aa89b499d263011d2fc8fd522d7e20efb4c6d2b5/scrapers/nus-v2/src/services/requisite-tree/normalizeString.ts), and tested with unit tests in [this file](https://github.com/nusmodifications/nusmods/blob/aa89b499d263011d2fc8fd522d7e20efb4c6d2b5/scrapers/nus-v2/src/services/requisite-tree/normalizeString.test.ts).

**Comment by andlimey** [comment]
Anyone handling this? @taneliang
