### ISSUE TITLE
Home and End keys doesn't work in some text inputs

### ISSUE THREAD

**Issue by davidchoo12** [nusmodifications/nusmods#2733]
### Describe the bug

Pressing home/end keys in the "search module" and "add module to timetable" text inputs does not work. The keys work fine in "search venue" text field. Same for shift+home and shift+end to highlight text in the fields.

Update: I just realized home and end keys are binded to the dropdown in the search fields. Pressing home focuses on first search result in dropdown, end focuses on last search result. I prefer to have them move the cursor though, since that's the default behaviour on normal text inputs.

### To Reproduce

1. Select the search module input
2. Type something in it
3. Press home key, cursor stays in position
4. Move cursor to start, press end key, cursor stays in position

### Expected behavior

Home key should move cursor to start, end key should move cursor to end.
Refer to "search venue" field or any text input field online for normal behavior.

### Desktop (please complete the following information):

* OS: Windows 10 v1909
* Browser: Firefox v78.0.2

**Comment by taneliang** [comment]
Hmm, that's because both of those search boxes (managed by Downshift) try to mimic the behavior of `<select>` dropdowns. Some other things that Downshift does is bind the up/down arrow keys to navigate between the displayed options. I don't think we'll want to try to override a subset of this behavior as it'll then be inconsistent with *both* regular text inputs and dropdowns. Thanks for the suggestion though!
