### ISSUE TITLE
MA1101R and MA1102R prerequisites not updated

### ISSUE THREAD

**Issue by RussellDash332** [nusmodifications/nusmods#3333]
### Describe the bug

MA1101R and MA1102R have been recoded to MA2001 and MA2002 but the prerequisite feature doesn't apply to NUSMods Planner

### To Reproduce

1. Go to Planner (turn on NUSMods Beta)
2. Pick MA2001 and ST2131 on one same semester then DSA2101 on the next sem
3. See error

### Expected behavior

A warning says that MA1101R has to be taken first but it's already MA2001 now. MA1101R has no data instead.

### Screenshots

![image](https://user-images.githubusercontent.com/63991775/127779550-3ddad477-8801-48ee-b4f4-82b30752ee77.png)

### Desktop (please complete the following information):

- OS: Windows 64-bit
- Browser: Chrome

**Comment by RussellDash332** [comment]
I have a better picture. The red lines show the prerequisites that are fine. The blue dotted lines are the error.
![image](https://user-images.githubusercontent.com/63991775/128424285-6ce4413b-7ae1-4728-8fa2-1d09863c5ac3.png)

**Comment by chrisgzf** [comment]
The issue arises because the module data provided by NUS doesn't accurately list the prerequisites.

Here is an example of a mod that does it properly: https://nusmods.com/modules/MA2214/combinatorics-and-graphs-i, they list both `MA2001 or MA1101R`.

The mod with these issues do not list their prereqs properly. For example, CS3244 has `(MA1101R or MA1311 or MA1508E or MA1513)`.

If you'd like to get this fixed, I'll suggest you write to the UG offices for these mods and request for them to include the recoded modules in their prereqs. It's difficult for us to fix it from our part because we'd have to maintain our list of same-but-recoded modules, which is costly to maintain. Closing for now.
