### ISSUE TITLE
Unable to search for mod when window resized

### ISSUE THREAD

**Issue by heyzec** [nusmodifications/nusmods#3365]
### Describe the bug
If the browser app is resized such that it is not full screen, e.g. tiled to the left half of screen, the search icon disappears, and you can no longer do any searches.

### To Reproduce

1. Just resize your screen.

![Screenshot from 2021-11-11 00-19-13](https://user-images.githubusercontent.com/61238538/141151361-ed93ce52-4e45-492e-81c1-d99dadefb629.png)

### Desktop (please complete the following information):

- OS: Ubuntu 20.04
- Browser: Tested on both Firefox 94.0 and Chromium 95.0

**Comment by chrisgzf** [comment]
What is your screen resolution?

This happens when the size of the viewport is resized below a width of 768px. Below that point, NUSMods reflows content to fit a mobile viewport, which does not have the search icon. 768px is a convention that we follow because it is one of the most common breakpoints for responsive web design (most other responsive websites follow the same breakpoints), and I don't think we intend to change this to support this specific use case.

**Comment by chrisgzf** [comment]
Also, you can still search for modules in the mobile viewport by going to the modules page (3rd icon at the top).
