### ISSUE TITLE
[Design] Endless Pagination

### ISSUE THREAD

**Issue by 9gix** [nusmodifications/nusmods#35]
I have been questioning about the endless pagination in many sites, because I find myself quite annoyed because I was overwhelmed by lots of content in the page. 

In short, I still prefer the simple pagination for NUSmods listing.

Here's an article that discuss about endless pagination.
http://ux.stackexchange.com/a/33408/43219

**Comment by ngzhian** [comment]
What's the consensus on this? I'm for simple pagination too :)

**Comment by yangshun** [comment]
No consensus since we never had the discussion. Personally fine with either (:

**Comment by ngzhian** [comment]
@ahbeng big boss, wdyt?

**Comment by ahbeng** [comment]
@ngzhian I'm fine either way. Endless pagination was actually more convenient to implement. Otherwise might have to think about URL design.

I think this is quite low priority since it doesn't add any additional functionality and is more a personal preference. To avoid potentially wasting effort, it should be considered in tandem with switching to server-side filtering.

**Comment by yangshun** [comment]
@ngzhian hmm let’s deprioritize this until we have come up with a scope for it

**Comment by yangshun** [comment]
We'll go with infinite scrolling.
