### ISSUE TITLE
Course Planner "Plan to Take" and "Exemptions" sections don't have course autofill feature

### ISSUE THREAD

**Issue by dingZvel** [nusmodifications/nusmods#3650]
### Describe the bug

The "Plan to Take" and "Exemptions" sections don't have the course autofill feature as Year X Semester X sections

### To Reproduce

1. Click the "+ Add Courses" buttons in **Exemptions** and **Plan to Take** sections
2. Type in for example "cs", "ma' or things like that
3.  No completion suggestions will show up for users to autofill.

### Expected behavior

Should pop up completion suggestions menu for users to autofill the course, which is the behavior when testing in the above "Year X Semester X" sections

### Desktop (please complete the following information):

- Browser: Brave

**Comment by ravern** [comment]
This probably has something to do with wrong props being passed to the `PlannerModuleSelect` component.

https://github.com/nusmodifications/nusmods/blob/089993f56557c729572284b762384424f7806d53/website/src/views/planner/AddModule.tsx#L102-L108

I'm labelling this as a good first issue since this seems like a simple UI bug!

**Comment by ravern** [comment]
I think a tangential issue that can be solved in the same PR is the confusion (because there's no dropdown) that the Add Course button here should be adding the course I enter in the text input.

<img width="227" alt="image" src="https://github.com/nusmodifications/nusmods/assets/22592318/4ca1c930-958b-4472-8622-7bfd51a5b3af">

Perhaps something even better would be renaming the text in the button from "Add Course" to "Add Category" or something that avoids this confusion entirely.

**Comment by kokrui** [comment]
+1 to renaming to "Add Category"

**Comment by wr1159** [comment]
Hi I am interested in taking this issue
