### ISSUE TITLE
Course Planner - Does not recognise prerequisite

### ISSUE THREAD

**Issue by somebodyelsedidthis** [nusmodifications/nusmods#3733]
### Describe the bug

An NUSC course has a prerequisite of any NTW-coded course, but does not reflect the prerequisite being cleared despite an NTW-coded module being taken earlier in the course plan

### To Reproduce

1. Select any NTWxxxx course in Y1 in the course planner
2. Select any NHSxxxx course in Y2 in the course planner

### Expected behavior

The NHS course should not be yellow, and should reflect the prerequisite being cleared

### Screenshots

![image](https://github.com/nusmodifications/nusmods/assets/46418783/04005949-bea5-479c-a587-101b6fc6020e)

### Desktop (please complete the following information):

- OS: Windows 11 Pro v. 23H2
- Browser: Chrome
- Version 125.0.6422.142

### Additional context

There are various NTW coded modules, any of which can clear the prerequisite for any of the NHS modules.

**Comment by frymash** [comment]
This bug can also be reproduced for courses under the UTown College Programme (i.e. courses belonging to CAPT, RC4, and Tembusu College).

For these colleges, Junior Seminars (JS; UTC11%/UTC14%/UTC17%) are prereqs for Senior Seminars (SS; UTC21%/UTC24%/UTC27%/UTS21%/UTS24%/UTS27%). However, even if you insert a JS before a SS in the planner, the planner will not recognise that the SS' prereq has already been cleared.

In the pic below, UTC2400 in Y2S1 should be green and shouldn't display a prereq warning since UTC1402 was listed under Y1S1.

<img width="655" alt="Screenshot 2024-06-13 at 2 48 54 PM" src="https://github.com/nusmodifications/nusmods/assets/42537694/3d5b2052-8d39-4d37-90d9-d22984220c3c">
<br><br>

The steps to reproduce the bug are almost identical to the steps @somebodyelsedidthis wrote earlier:
1. Select any JS in Y1 in the course planner
2. Select any SS in Y2 in the course planner
3. See error

**Comment by kokrui** [comment]
Thanks for opening this issue! My understanding is that this generally applies to any pre-requisites that are not an actual course, and instead "wildcards" like "any Courses beginning with XYZ" or "AB1234%". We'd be happy to help with and approve PRs that work on this!
