### ISSUE TITLE
Planner ModuleMenu overlaps with the next menu's icon

### ISSUE THREAD

**Issue by leslieyip02** [nusmodifications/nusmods#3739]
### Describe the bug

The planner's `ModuleMenu` overlaps with the dropdown caret icon of the next module.

### To Reproduce

1. Go to Planner
2. Select 2 mods (the first mod needs to be a one-liner, if not the menu will not overlap with the next mod)
3. See error

### Expected behavior
Menus should not overlap.

### Screenshots

![Screenshot 2024-07-05 202400](https://github.com/nusmodifications/nusmods/assets/90888680/14fa8f71-d750-4695-b6f7-164eca102d25)

![Screenshot 2024-07-05 202711](https://github.com/nusmodifications/nusmods/assets/90888680/5d83f3e6-8746-4f17-abe3-e54ad3c28dd8)

### Desktop

- OS: Windows 11
- Browser: Tested on Firefox and Chrome

**Comment by kokrui** [comment]
Thanks for the report! This is a regression from some Content-Security-Policy changes we've had to make recently, let me fix it real quick

**Comment by iZUMi-kyouka** [comment]
The issue seems to be in website\src\views\planner\PlannerModule.scss

With the `z-index: 1;` and `position: relative;` in the .menuBtn, a new stacking context is created which includes the menu popup, since the actual popup is inside the button, so setting z-index of 910 in .dropdown-menu in caret.scss (which I couldn't find in the forked repo) won't cause it to be in front of the next menu button causing overlap (cmiiw).

![image](https://github.com/nusmodifications/nusmods/assets/164025287/34f88cb0-f991-4f26-9ec3-0dd0016e8c45)

Removing z-index: 1 from .menuBtn in PlannerModule.scss seems to fix the issue.

![image](https://github.com/nusmodifications/nusmods/assets/164025287/dba484e3-64b3-47a4-b181-a2d15ec38277)
z-index is removed

![image](https://github.com/nusmodifications/nusmods/assets/164025287/17f167e8-fed4-4837-b76b-3baf14bdd332)
![image](https://github.com/nusmodifications/nusmods/assets/164025287/f02b3be7-eb4f-4295-89f4-e3807cf21cae)
menu no longer overlaps with the next button in this specific case
