### ISSUE TITLE
Refactor theme store to account for semester-specific module colors

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#511]
There's a bug where:

1. Add module X to sem 1
2. Add module X to sem 2
3. Remove module X from sem 1
4. Module X in sem 2 loses its color

This is because the `theme` reducer maps a module to a color. There’s no notion of semesters in it. I refactor should take place such that a color is tied to each module within a semester instead. Two ways to do it:

1. Add a color property into `Module` object.
2. Differentiate by semesters within the `theme` reducer.

I'm leaning towards the first approach because eventually we need to differentiate by acad years also and doing the first approach is more future proof when that change happens.

**Comment by ZhangYiJiang** [comment]
I wonder if it is possible to move the `ColorMapping` object under the timetables reducer. This makes it simpler since all it needs to do is to compare the previous and next timetable state and check that 

- Any modules in the color map that's not in the timetable can be dropped 
- Any modules on the timetable that's not in the color map can be assigned a color
