### ISSUE TITLE
RFC: Monorepo format

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#595]
Proposal: Bring over repos like [nusmods-api](https://github.com/nusmodifications/nusmods-api) and [nusmoderator](https://github.com/nusmodifications/nusmoderator) under this repo.

Justification: Less noise and more discoverability (we have quite a few repos), and we have some scripts in v3 that is more scraping related already. Commit level consistency is icing on cake.

How: Yarn provides [workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) which make common node_modules quite simple. No need to maintain 3 babelrc & eslintrc too :D

**Comment by ZhangYiJiang** [comment]
How does this affect deployment and publishing (for nusmoderator)? Otherwise, this looks pretty good.

**Comment by li-kai** [comment]
Not very different from how we already do it, just cd nusmoderator and yarn publish.

**Comment by yangshun** [comment]
I generally agree to merge `nusmods-api` and `nusmoderator` in, so that we can share some of tooling config and possibly use R's Flowtypes in `nusmods-api`. Basically this monorepo should only contains stuff directly related to NUSMods, and not the sister products.

Considerations:
- Repo CI times. At my previous company I wrote some scripts to identify the projects which changed and then proceed with the CI for those projects which have changed.
- Ability to have a dedicated `gh-pages` just for the repo. So I don't think https://github.com/nusmodifications/nus-exams-downloader should come under the monorepo. Also, it's in Python. https://github.com/nusmodifications/nusmods-blog also probably shouldn't if we were thinking about that.

Other repo management tools to consider (I don't know the differences):

- https://github.com/boltpkg/bolt (by author of Yarn, James Kyle)
- https://github.com/lerna/lerna (yet another one by James Kyle)
- https://github.com/guigrpa/oao

Related readings:

- https://staltz.com/setting-up-a-javascript-monorepo.html
- https://danluu.com/monorepo/
- https://github.com/babel/babel/blob/master/doc/design/monorepo.md

**Comment by ZhangYiJiang** [comment]
I believe this has been completed via #610 and #611
