### ISSUE TITLE
No feedback on successful addition of module to timetable on mobile

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#598]
Steps to reproduce:

1. View site on mobile
2. Go to /timetable
3. Tap on "Add module to timetable" input
4. Key in some text and add any module
5. Search term and results disappear with no indication of success/failure.

One solution I have is to retain the search term and results screen so that the `Added` label appears and the user will know that the operation was successful. I think it's ok to leave the search term and results there as people usually add modules from the same faculty anyway.

![image 2017-12-27 00 24 02](https://user-images.githubusercontent.com/1315101/34375616-4095805c-ea9c-11e7-8bd5-c248d237523a.jpg)

**Comment by ZhangYiJiang** [comment]
It's actually a problem on desktop too, since the process is async there may be a small lag between hitting enter on the keyboard or clicking and the item actually appearing, so we need some sort of spinner to inform the user. Here's my idea - use the dropdown menu itself to do this - 

- When an item is entered, the hint text turns into a small spinner and the text 'Adding {ModuleCode} {ModuleTitle}...'. On desktop this can be bigger (icon above text instead of inline) since we have more space. 
- Once the module is added, on mobile the hint text returns. On desktop the modal can just clear itself. 

I think this is better than using a toast stuck to the bottom of the screen (which also doesn't work on iOS). Comments?

**Comment by yangshun** [comment]
That sounds really good!

**Comment by taneliang** [comment]
Implemented in #655

**Comment by ZhangYiJiang** [comment]
I actually don't think this should be closed, because there's still the async problem - basically modules are added asynchronously, but currently there's no spinner, so it looks as if your input is lagging when you add a module not in the module bank. We could open another issue for that though.

**Comment by taneliang** [comment]
That's true. That's a different issue though. I'll open one for that
