### ISSUE TITLE
Reduce code duplication in utils/ical 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#726]
There's a bunch of duplicated logic between `utils/ical`, `utils/timify` and `utils/modules`  - mainly small utility functions like `getTimeHour` and `getExamDate`. 

Deduplicating the code should make the code more maintainable and less bug prone.

**Comment by li-kai** [comment]
Might be better to take a look at https://date-fns.org/docs/Getting-Started or https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html luxon looks more suited for operations we're doing.

**Comment by wenmogu** [comment]
Can I take this issue

**Comment by taneliang** [comment]
Sure! I don't think anyone of us is working on this now

**Comment by seanlowjk** [comment]
Hi, may I know if this issue is up for grabs? Since the migration of our functions to use `Moment.js/luxon` would be great instead of having of current functions. And as a result, reduce the amount of code that we would need to maintain as a result to! 

Do let me know if it is alright for me to do so >< @chrisgzf @taneliang @li-kai @ZhangYiJiang 

cc @wenmogu if you are still taking on this issue
